[package]
name = "rcall"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
dirs = "5.0"
tesseract = "0.15.2"
rake = "0.1"
rusqlite = { version = "0.31", features = ["bundled", "modern_sqlite"] }
clap = { version = "4.4", features = ["derive"] }
